language: objective-c
cache:
  directories:
    - something-to-cache
script:
  - "touch something-to-cache/$(date '+%s')"
  - "ls something-to-cache"
after_success:
  - "for f in ~/.casher/*; do echo $f; cat $f; echo; done"
